# Generated by Django 5.0.1 on 2024-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=50)),
                ('dealer_email', models.EmailField(max_length=254)),
                ('dealer_contact', models.CharField(max_length=50)),
                ('dealer_auth', models.CharField(max_length=50)),
                ('dealer_pass', models.CharField(max_length=50)),
                ('dealer_join', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_auth', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_join', models.DateTimeField()),
            ],
        ),
    ]
