# Generated by Django 5.0.1 on 2024-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='userimages')),
            ],
        ),
        migrations.AlterField(
            model_name='registerdealer',
            name='dealer_join',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
