# Generated by Django 5.0.1 on 2024-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_images_alter_registerdealer_dealer_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
