# Generated by Django 5.0.1 on 2024-02-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_alter_images_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='photo',
            new_name='image',
        ),
    ]
