# Generated by Django 5.0.1 on 2024-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_productadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadd',
            name='dealer_id',
            field=models.IntegerField(blank=True),
        ),
    ]
